### ISSUE TITLE
I can't figure out how to change tooltip text to another language

### ISSUE THREAD

**Issue by gekh** [editor-js/inline-code#14]
I tried different configs but didn't find an option to change tooltip text from “InlineCode” to “Код”.
If there is an option, please help me. If there is not, then please add it.

**Comment by SalahAdDin** [comment]
> I tried different configs but didn't find an option to change the tooltip text from “InlineCode” to “Код”. If there is an option, please help me. If there is not, then please add it.

I can't find any tooltip text in the code; for implementing it we should require both updating this plugin to the last API and implementing the `i18n` API too.

**Comment by neSpecc** [comment]
It could be achieved using the [i18n feature](https://editorjs.io/i18n). Try specifying `toolNames` property for that tool
